[package]
name = "new_grader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
libc = "0.2.169"
rayon = "1.10.0"
tempdir = "0.3.7"
thiserror = "2.0.9"
